style:
- btn-text-color: "#fff"
- btn-background-color: "#53C5E3"
- height: 550px
text:
  title: Feature Title
  first-feature-title: First Title
  first-feature-body: First Body,Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
  second-feature-title: Second Title
  second-feature-body: Second Body,Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
  third-feature-title: Third Title
  third-feature-body: Third Body,Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
  button: More About Our Mission
images:
  first-feature: heart.png
  second-feature: map.png
  third-feature: calendar.png
variables:
